name: inventaris
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.2
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  dio: ^4.0.0
  quickalert: ^1.0.2
  line_awesome_flutter: ^2.0.0
  lottie: ^2.7.0
  intl: ^0.19.0
  flutter_onboarding_screen: ^2.0.2
  flutter_onboarding_slider: ^1.0.11
  url_launcher: ^6.2.2


dev_dependencies:
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icapp.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - animation/

